language: c

dist: xenial

matrix:
  include:
   - env: GHCVER=8.6.3
     os: linux
     sudo: required
   - env: GHCVER=8.6.2
     os: linux
     sudo: required
   - env: GHCVER=8.6.1
     os: linux
     sudo: required
   - env: GHCVER=8.4.4
     os: linux
     sudo: required
   - env: GHCVER=8.4.3
     os: linux
     sudo: required
   - env: GHCVER=8.4.2
     os: linux
     sudo: required
   - env: GHCVER=8.4.1
     os: linux
     sudo: required
   - env: GHCVER=8.2.2
     os: linux
     sudo: required
   - env: GHCVER=8.2.1
     os: linux
     sudo: required
   - env: GHCVER=8.0.2
     os: linux
     sudo: required
   - env: GHCVER=8.0.1
     os: linux
     sudo: required
   - env: GHCVER=7.10.3
     os: linux
     sudo: required
   - env: GHCVER=7.10.2
     os: linux
     sudo: required
   - env: GHCVER=7.10.1
     os: linux
     sudo: required

   - env: GHCVER=8.6.3
     os: osx
   - env: GHCVER=8.0.2
     os: osx

before_install:
  - .ci/travis-install.sh
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/2.4/bin:$PATH";
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH";
    fi

install:
  - cabal new-update

script:
  - cabal new-build -j --enable-tests -fexamples
  - cabal new-test -j
  - cabal new-run -fexamples leveldb-example-comparator
  - cabal new-run -fexamples leveldb-example-features
  - cabal new-run -fexamples leveldb-example-filterpolicy
  - cabal new-run -fexamples leveldb-example-iterforkio

cache:
  directories:
    - $HOME/.cabal/packages
    - $HOME/.cabal/store
    - $HOME/.cabal/bin
    - $HOME/.ghcup

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index*
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index*
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
  - rm -rfv $HOME/.cabal/packages/hackage.haskell.org/hackage-security-lock
