env:
  - GHCVER=7.10.1
  - GHCVER=8.0.1
  - GHCVER=8.2.1
  - GHCVER=8.2.2
  - GHCVER=8.4.1
  - GHCVER=8.4.2
  - GHCVER=8.4.3
  - GHCVER=8.4.4
  - GHCVER=8.6.1
  - GHCVER=8.6.2

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo add-apt-repository -y ppa:openstack-ubuntu-testing/icehouse
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-1.24 ghc-$GHCVER libleveldb-dev libsnappy-dev
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.24/bin:$PATH

install:
  - cabal update
  - cabal install -j --only-dependencies --enable-tests --enable-documentation

script:
  - cabal check
  - cabal sdist

  - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}');
    cd dist/;
    if [ -f "$SRC_TGZ" ]; then
      cabal install --run-tests --enable-documentation -fexamples "$SRC_TGZ";
    else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
    fi
